# Base configuration
database:
  sqlite:
    path: "./data/crypto.db"
    tables:
      ohlcv: "ohlcv"
      signals: "trading_signals"

models:
  lstm:
    lookback_window: 60
    epochs: 50
    batch_size: 32
    train_test_split: 0.8

logging:
  enabled: true
  log_file: "./logs/scraper.log"
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR

error_handling:
  max_retries: 5
  retry_backoff_factor: 2  # Exponential backoff strategy
